using System.Collections.Generic;

namespace JEMTools.Platforms
{
    public static class macOSModules
    {
        public static List<ToolItem> GetTools()
        {
            var tools = new List<ToolItem>();
            
            // --- MAINTENANCE (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Software Update", Command = "softwareupdate -l", Icon = "⚡", Category = "MAINTENANCE", Description = "Check for system software updates.", Guide = "Lists all available macOS system updates from Apple servers.", ManualLaunch = "softwareupdate -l", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Clear User Cache", Command = "rm -rf ~/Library/Caches/*", Icon = "🧹", Category = "MAINTENANCE", Description = "Purge local user cache files.", Guide = "Deletes cached data for the current user to resolve app issues.", ManualLaunch = "rm -rf ~/Library/Caches/*", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Clear System Cache", Command = "sudo rm -rf /Library/Caches/*", Icon = "📂", Category = "MAINTENANCE", Description = "Purge system-wide cache files.", Guide = "Requires root. Clears global system caches for performance.", ManualLaunch = "sudo rm -rf /Library/Caches/*", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Reset Permissions", Command = "diskutil resetUserPermissions / `id -u`", Icon = "🔧", Category = "MAINTENANCE", Description = "Fix home directory permissions.", Guide = "Restores default permissions for the current user's home folder.", ManualLaunch = "diskutil resetUserPermissions", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Purge Memory", Command = "sudo purge", Icon = "📊", Category = "MAINTENANCE", Description = "Force flush disk buffers/cache.", Guide = "Releases inactive memory back to the system. Requires sudo.", ManualLaunch = "sudo purge", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Spotlight Re-index", Command = "sudo mdutil -E /", Icon = "🔍", Category = "MAINTENANCE", Description = "Rebuild Spotlight search index.", Guide = "Erases and rebuilds the metadata index for the primary drive.", ManualLaunch = "sudo mdutil -E /", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Launch Services Reset", Command = "/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user", Icon = "🚀", Category = "MAINTENANCE", Description = "Rebuild app association database.", Guide = "Fixes broken 'Open With' menus and duplicate app entries.", ManualLaunch = "lsregister -kill", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Battery Health", Command = "pmset -g batt", Icon = "🔋", Category = "MAINTENANCE", Description = "Check battery power status.", Guide = "Displays current battery percentage, health, and power source.", ManualLaunch = "pmset -g batt" });
            tools.Add(new ToolItem { SpecificName = "System Sleep Image", Command = "ls -lh /var/vm/sleepimage", Icon = "🌙", Category = "MAINTENANCE", Description = "Check hibernation file size.", Guide = "Displays the size of the system's hibernation/sleep storage file.", ManualLaunch = "ls /var/vm/sleepimage" });
            tools.Add(new ToolItem { SpecificName = "System Restart", Command = "sudo shutdown -r now", Icon = "🔄", Category = "MAINTENANCE", Description = "Immediate system reboot.", Guide = "Performs an immediate graceful restart of the macOS system.", ManualLaunch = "sudo shutdown -r now", IsMacro = true });

            // --- SYSTEM (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Activity Monitor", Command = "open -a 'Activity Monitor'", Icon = "📋", Category = "SYSTEM", Description = "Monitor processes and resources.", Guide = "macOS graphical task manager for CPU, Memory, Disk, and Energy.", ManualLaunch = "open -a 'Activity Monitor'" });
            tools.Add(new ToolItem { SpecificName = "System Information", Command = "open -a 'System Information'", Icon = "ℹ️", Category = "SYSTEM", Description = "Detailed HW/SW specifications.", Guide = "Comprehensive report on all hardware and software components.", ManualLaunch = "open -a 'System Information'" });
            tools.Add(new ToolItem { SpecificName = "Hardware Profiler", Command = "system_profiler SPHardwareDataType", Icon = "💻", Category = "SYSTEM", Description = "CLI hardware summary.", Guide = "Displays model name, processor, memory, and serial number info.", ManualLaunch = "system_profiler" });
            tools.Add(new ToolItem { SpecificName = "CPU Brand String", Command = "sysctl -n machdep.cpu.brand_string", Icon = "⚙️", Category = "SYSTEM", Description = "Detailed processor model.", Guide = "Shows the exact manufacturer and model of the CPU.", ManualLaunch = "sysctl" });
            tools.Add(new ToolItem { SpecificName = "Memory Capacity", Command = "sysctl hw.memsize", Icon = "📊", Category = "SYSTEM", Description = "Total physical RAM in bytes.", Guide = "Calculates and displays the total system memory capacity.", ManualLaunch = "sysctl hw.memsize" });
            tools.Add(new ToolItem { SpecificName = "Kernel Version", Command = "uname -v", Icon = "🐧", Category = "SYSTEM", Description = "Darwin kernel build info.", Guide = "Shows the kernel version string and build timestamp.", ManualLaunch = "uname -v" });
            tools.Add(new ToolItem { SpecificName = "macOS Version", Command = "sw_vers", Icon = "🍎", Category = "SYSTEM", Description = "Operating system build details.", Guide = "Displays the macOS name, product version, and build number.", ManualLaunch = "sw_vers" });
            tools.Add(new ToolItem { SpecificName = "Loaded Extensions", Command = "kextstat", Icon = "📦", Category = "SYSTEM", Description = "List active kernel extensions.", Guide = "Displays all kernel modules (drivers) currently in memory.", ManualLaunch = "kextstat" });
            tools.Add(new ToolItem { SpecificName = "Boot Arguments", Command = "nvram -p", Icon = "🏁", Category = "SYSTEM", Description = "View NVRAM boot parameters.", Guide = "Lists all non-volatile RAM variables including boot-args.", ManualLaunch = "nvram -p" });
            tools.Add(new ToolItem { SpecificName = "Terminal Shell", Command = "open -a 'Terminal'", Icon = "🐚", Category = "SYSTEM", Description = "Standard macOS terminal.", Guide = "Opens the default Zsh/Bash command line interface.", ManualLaunch = "open -a 'Terminal'" });

            // --- ADMIN (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Service List", Command = "launchctl list", Icon = "⚙️", Category = "ADMIN", Description = "List managed services.", Guide = "Displays all launchd agents and daemons currently registered.", ManualLaunch = "launchctl list" });
            tools.Add(new ToolItem { SpecificName = "Disk Utility", Command = "open -a 'Disk Utility'", Icon = "💽", Category = "ADMIN", Description = "Graphical disk management.", Guide = "Tool for formatting, partitioning, and repairing disks via First Aid.", ManualLaunch = "open -a 'Disk Utility'" });
            tools.Add(new ToolItem { SpecificName = "Console Logs", Command = "open -a 'Console'", Icon = "📜", Category = "ADMIN", Description = "System and app log viewer.", Guide = "Unified log viewer for system events and application errors.", ManualLaunch = "open -a 'Console'" });
            tools.Add(new ToolItem { SpecificName = "User Accounts", Command = "dscl . list /Users", Icon = "👥", Category = "ADMIN", Description = "List all system users.", Guide = "Retrieves a list of all local user accounts from Open Directory.", ManualLaunch = "dscl . list /Users" });
            tools.Add(new ToolItem { SpecificName = "Group Accounts", Command = "dscl . list /Groups", Icon = "👤", Category = "ADMIN", Description = "List all system groups.", Guide = "Retrieves a list of all local groups defined in the system.", ManualLaunch = "dscl . list /Groups" });
            tools.Add(new ToolItem { SpecificName = "Directory Utility", Command = "open -a 'Directory Utility'", Icon = "🗄️", Category = "ADMIN", Description = "Advanced directory config.", Guide = "Manage LDAP, Active Directory, and Open Directory connections.", ManualLaunch = "open -a 'Directory Utility'" });
            tools.Add(new ToolItem { SpecificName = "Screen Sharing", Command = "open -a 'Screen Sharing'", Icon = "📡", Category = "ADMIN", Description = "Remote desktop client.", Guide = "Connect to and control other macOS computers on the network.", ManualLaunch = "open -a 'Screen Sharing'" });
            tools.Add(new ToolItem { SpecificName = "System Uptime", Command = "uptime", Icon = "⏱️", Category = "ADMIN", Description = "Check time since last boot.", Guide = "Displays how long the system has been running since the last restart.", ManualLaunch = "uptime" });
            tools.Add(new ToolItem { SpecificName = "Power Management", Command = "pmset -g", Icon = "🔌", Category = "ADMIN", Description = "View energy saver settings.", Guide = "Displays current sleep, wake, and display power configurations.", ManualLaunch = "pmset -g" });
            tools.Add(new ToolItem { SpecificName = "Scheduled Events", Command = "pmset -g sched", Icon = "📅", Category = "ADMIN", Description = "View wake/sleep schedule.", Guide = "Lists all repeating power events like scheduled startup or sleep.", ManualLaunch = "pmset -g sched" });

            // --- SECURITY (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Firewall Status", Command = "defaults read /Library/Preferences/com.apple.alf globalstate", Icon = "🛡️", Category = "SECURITY", Description = "Check Application Firewall.", Guide = "Indicates if the macOS Application Layer Firewall is active (1) or inactive (0).", ManualLaunch = "defaults read alf" });
            tools.Add(new ToolItem { SpecificName = "Gatekeeper Info", Command = "spctl --status", Icon = "🔒", Category = "SECURITY", Description = "Audit app security policy.", Guide = "Indicates if Gatekeeper is enforcing code signature requirements.", ManualLaunch = "spctl --status" });
            tools.Add(new ToolItem { SpecificName = "FileVault Status", Command = "fdesetup status", Icon = "🧱", Category = "SECURITY", Description = "Check disk encryption.", Guide = "Displays the current status of FileVault full-disk encryption.", ManualLaunch = "fdesetup status" });
            tools.Add(new ToolItem { SpecificName = "Open Network Files", Command = "lsof -i", Icon = "📂", Category = "SECURITY", Description = "List files with network IDs.", Guide = "Shows which apps are using network connections to open files.", ManualLaunch = "lsof -i" });
            tools.Add(new ToolItem { SpecificName = "Listening Ports", Command = "sudo lsof -i -P | grep LISTEN", Icon = "🔒", Category = "SECURITY", Description = "Audit active listeners.", Guide = "Identifies which processes are listening on network ports.", ManualLaunch = "lsof -i -P | grep LISTEN" });
            tools.Add(new ToolItem { SpecificName = "Login Items", Command = "osascript -e 'tell application \"System Events\" to get the name of every login item'", Icon = "🗝️", Category = "SECURITY", Description = "List startup applications.", Guide = "Retrieves names of all apps configured to launch at login.", ManualLaunch = "osascript login items" });
            tools.Add(new ToolItem { SpecificName = "Security Audit", Command = "security find-identity -p codesigning", Icon = "🖋️", Category = "SECURITY", Description = "Audit code sign identities.", Guide = "Lists all valid code-signing certificates in the user's keychain.", ManualLaunch = "security find-identity" });
            tools.Add(new ToolItem { SpecificName = "Keychain Info", Command = "security list-keychains", Icon = "🗝️", Category = "SECURITY", Description = "List active keychains.", Guide = "Shows all keychain files currently being searched by the system.", ManualLaunch = "security list-keychains" });
            tools.Add(new ToolItem { SpecificName = "Remote Login", Command = "sudo systemsetup -getremotelogin", Icon = "📡", Category = "SECURITY", Description = "Check SSH/SFTP status.", Guide = "Indicates if remote SSH login is enabled on the system.", ManualLaunch = "systemsetup -getremotelogin" });
            tools.Add(new ToolItem { SpecificName = "Firmware Security", Command = "sudo firmwarepasswd -check", Icon = "🔐", Category = "SECURITY", Description = "Check EFI password status.", Guide = "Checks if a firmware password is set to protect the boot process.", ManualLaunch = "firmwarepasswd -check" });

            // --- NETWORK (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "IP Configuration", Command = "ifconfig", Icon = "🔍", Category = "NETWORK", Description = "Detailed interface diagnostics.", Guide = "Displays IP addresses, MAC addresses, and status of all adapters.", ManualLaunch = "ifconfig" });
            tools.Add(new ToolItem { SpecificName = "DNS Cache Flush", Command = "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder", Icon = "🧼", Category = "NETWORK", Description = "Purge DNS resolver cache.", Guide = "Clears local DNS entries. Resolves stale domain resolution issues.", ManualLaunch = "dscacheutil -flushcache", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Wi-Fi Profile", Command = "/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I", Icon = "📡", Category = "NETWORK", Description = "Detailed Wi-Fi connection info.", Guide = "Shows SSID, BSSID, RSSI, and data rates for the current Wi-Fi link.", ManualLaunch = "airport -I" });
            tools.Add(new ToolItem { SpecificName = "Connectivity Test", Command = "ping -c 4 google.com", Icon = "🔄", Category = "NETWORK", Description = "Check internet latency.", Guide = "Sends 4 ICMP packets to verify connectivity to Google.", ManualLaunch = "ping google.com" });
            tools.Add(new ToolItem { SpecificName = "Trace Route", Command = "traceroute google.com", Icon = "📶", Category = "NETWORK", Description = "Map network hop paths.", Guide = "Shows every router between you and a network destination.", ManualLaunch = "traceroute" });
            tools.Add(new ToolItem { SpecificName = "Network Diagnostics", Command = "open /System/Library/CoreServices/Applications/Network\\ Utility.app", Icon = "🛠️", Category = "NETWORK", Description = "Legacy network toolkit.", Guide = "Opens the legacy Network Utility app (if available on current macOS).", ManualLaunch = "open Network Utility" });
            tools.Add(new ToolItem { SpecificName = "Active Routing", Command = "netstat -nr", Icon = "🗺️", Category = "NETWORK", Description = "Analyze routing table.", Guide = "Displays the kernel routing table and default gateways.", ManualLaunch = "netstat -nr" });
            tools.Add(new ToolItem { SpecificName = "ARP Table", Command = "arp -a", Icon = "👥", Category = "NETWORK", Description = "Analyze neighbor devices.", Guide = "Lists MAC-to-IP mappings for devices on the local network.", ManualLaunch = "arp -a" });
            tools.Add(new ToolItem { SpecificName = "DNS Query (Dig)", Command = "dig google.com", Icon = "🌐", Category = "NETWORK", Description = "Advanced DNS record lookup.", Guide = "Retrieves full DNS record data for any domain name.", ManualLaunch = "dig" });
            tools.Add(new ToolItem { SpecificName = "Interface Setup", Command = "networksetup -listallnetworkservices", Icon = "🔗", Category = "NETWORK", Description = "List all network services.", Guide = "Shows all services like Wi-Fi, Ethernet, and Bluetooth PAN.", ManualLaunch = "networksetup" });

            // --- UTILITIES (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "TextEdit", Command = "open -a 'TextEdit'", Icon = "📝", Category = "UTILITIES", Description = "Native plain text editor.", Guide = "Standard macOS text editor for quick note-taking and editing.", ManualLaunch = "open -a 'TextEdit'" });
            tools.Add(new ToolItem { SpecificName = "Finder", Command = "open .", Icon = "📁", Category = "UTILITIES", Description = "Open current directory.", Guide = "Launches the Finder file manager at the current working path.", ManualLaunch = "open ." });
            tools.Add(new ToolItem { SpecificName = "Ollama AI Core", Command = "ollama run llama3", Icon = "🧠", Category = "UTILITIES", Description = "Local AI deployment.", Guide = "Starts an interactive local session with the Llama3 AI model.", ManualLaunch = "ollama run llama3" });
            tools.Add(new ToolItem { SpecificName = "Calculator", Command = "open -a 'Calculator'", Icon = "🧮", Category = "UTILITIES", Description = "Native math utility.", Guide = "Standard macOS calculator with basic and scientific modes.", ManualLaunch = "open -a 'Calculator'" });
            tools.Add(new ToolItem { SpecificName = "Calendar", Command = "open -a 'Calendar'", Icon = "📅", Category = "UTILITIES", Description = "Schedule and events.", Guide = "Standard macOS calendar app for managing appointments.", ManualLaunch = "open -a 'Calendar'" });
            tools.Add(new ToolItem { SpecificName = "Screenshot Toolkit", Command = "open -a 'Screenshot'", Icon = "📸", Category = "UTILITIES", Description = "Capture screen images/video.", Guide = "Advanced overlay for capturing specific areas or windows.", ManualLaunch = "open -a 'Screenshot'" });
            tools.Add(new ToolItem { SpecificName = "Font Book", Command = "open -a 'Font Book'", Icon = "🔣", Category = "UTILITIES", Description = "Manage system fonts.", Guide = "Preview, install, and disable fonts across the macOS system.", ManualLaunch = "open -a 'Font Book'" });
            tools.Add(new ToolItem { SpecificName = "Keychain Access", Command = "open -a 'Keychain Access'", Icon = "🗝️", Category = "UTILITIES", Description = "Manage saved passwords.", Guide = "Centralized secure storage for passwords, keys, and certificates.", ManualLaunch = "open -a 'Keychain Access'" });
            tools.Add(new ToolItem { SpecificName = "ColorSync", Command = "open -a 'ColorSync Utility'", Icon = "🎨", Category = "UTILITIES", Description = "Display color management.", Guide = "Verify and repair color profiles for displays and printers.", ManualLaunch = "open -a 'ColorSync Utility'" });
            tools.Add(new ToolItem { SpecificName = "Script Editor", Command = "open -a 'Script Editor'", Icon = "📜", Category = "UTILITIES", Description = "AppleScript and JXA tool.", Guide = "Write and debug system-level automation scripts for macOS.", ManualLaunch = "open -a 'Script Editor'" });

            // --- JEMBOOT (3 Tools) ---
            tools.Add(new ToolItem { SpecificName = "List USB Drives", Command = "diskutil list external", Icon = "🔌", Category = "JEMBOOT", Description = "Identify connected USB media.", Guide = "Filters diskutil output to show only removable/external drives.", ManualLaunch = "diskutil list external" });
            tools.Add(new ToolItem { SpecificName = "Storage Usage", Command = "df -H", Icon = "💾", Category = "JEMBOOT", Description = "Analyze mount points.", Guide = "Displays disk usage for all mounted volumes in GB/TB format.", ManualLaunch = "df -H" });
            tools.Add(new ToolItem { SpecificName = "Verify Disk", Command = "diskutil verifyDisk /dev/disk2", Icon = "📀", Category = "JEMBOOT", Description = "Check disk partition map.", Guide = "Performs a low-level verification of the partition map integrity.", ManualLaunch = "diskutil verifyDisk" });
            // INSTALLERS
            tools.Add(new ToolItem { SpecificName = "Install 7-Zip", Command = "brew install p7zip", Icon = "📦", Category = "INSTALLERS", Description = "Open-source file archiver.", Guide = "Installs p7zip via Homebrew.", ManualLaunch = "brew install p7zip" });
            tools.Add(new ToolItem { SpecificName = "Install WinRAR", Command = "brew install unrar", Icon = "🗜️", Category = "INSTALLERS", Description = "Extraction utility.", Guide = "Installs unrar via Homebrew.", ManualLaunch = "brew install unrar" });
            tools.Add(new ToolItem { SpecificName = "Install PeaZip", Command = "brew install --cask peazip", Icon = "🗃️", Category = "INSTALLERS", Description = "Free archive manager.", Guide = "Installs PeaZip via Homebrew Cask.", ManualLaunch = "brew install --cask peazip" });
            tools.Add(new ToolItem { SpecificName = "Install VS Code", Command = "brew install --cask visual-studio-code", Icon = "💻", Category = "INSTALLERS", Description = "Modern source code editor.", Guide = "Installs Visual Studio Code.", ManualLaunch = "brew install --cask visual-studio-code" });
            tools.Add(new ToolItem { SpecificName = "Install Cursor", Command = "brew install --cask cursor", Icon = "🤖", Category = "INSTALLERS", Description = "AI-first code editor.", Guide = "Installs Cursor, the AI-powered IDE.", ManualLaunch = "brew install --cask cursor" });
            tools.Add(new ToolItem { SpecificName = "Install Eclipse", Command = "brew install --cask eclipse-java", Icon = "☕", Category = "INSTALLERS", Description = "Java Development IDE.", Guide = "Installs the Eclipse Java development environment.", ManualLaunch = "brew install --cask eclipse-java" });
            tools.Add(new ToolItem { SpecificName = "Install Blender", Command = "brew install --cask blender", Icon = "🎨", Category = "INSTALLERS", Description = "3D creation suite.", Guide = "Installs Blender 3D modeling and animation software.", ManualLaunch = "brew install --cask blender" });
                        tools.Add(new ToolItem { SpecificName = "Install Acrobat", Command = "brew install --cask adobe-acrobat-reader", Icon = "📄", Category = "INSTALLERS", Description = "PDF viewer by Adobe.", Guide = "Installs Adobe Acrobat Reader.", ManualLaunch = "brew install --cask adobe-acrobat-reader" });
            tools.Add(new ToolItem { SpecificName = "Install DaVinci Resolve", Command = "brew install --cask davinci-resolve", Icon = "🎬", Category = "INSTALLERS", Description = "Free video editor.", Guide = "Installs the free stable version of DaVinci Resolve (not Studio/Beta).", ManualLaunch = "brew install davinci-resolve" });
            tools.Add(new ToolItem { SpecificName = "Install Photoshop CS6 x64", Command = "open \"https://drive.google.com/file/d/108-MMr552-vNUg4ICd9_zo-ALn5AT7Oq/view?usp=drive_link\"", Icon = "🖼️", Category = "INSTALLERS", Description = "Download Portable CS6 (x64).", Guide = "Opens Google Drive to download the x64 portable version of Photoshop CS6.", ManualLaunch = "download ps cs6" });
            tools.Add(new ToolItem { SpecificName = "Install Photoshop CS6 x86", Command = "open \"https://drive.google.com/file/d/1bC498LjJy9308a8pHMJRQ1DUyyiMDcJ4/view?usp=drive_link\"", Icon = "🖌️", Category = "INSTALLERS", Description = "Download Portable CS6 (x86).", Guide = "Opens Google Drive to download the x86 portable version of Photoshop CS6.", ManualLaunch = "download ps cs6 32" });
            tools.Add(new ToolItem { SpecificName = "Install Photoshop CS3", Command = "open \"https://duckduckgo.com/?q=Photoshop+CS3+Portable+Mac\"", Icon = "🎨", Category = "INSTALLERS", Description = "Placeholder for CS3.", Guide = "Placeholder search for Photoshop CS3 portable version (pending Google Drive link).", ManualLaunch = "search ps cs3" });

            return tools;
        }
    }
}