using System.Collections.Generic;

namespace JEMTools.Platforms
{
    public static class LinuxModules
    {
        public static List<ToolItem> GetTools()
        {
            var tools = new List<ToolItem>();
            
            // --- MAINTENANCE (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "System Update", Command = "sudo apt update && sudo apt upgrade -y", Icon = "⚡", Category = "MAINTENANCE", Description = "Full system package synchronization.", Guide = "Synchronizes package indexes and upgrades all installed software.", ManualLaunch = "sudo apt update", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Package Cleanup", Command = "sudo apt autoremove -y && sudo apt clean", Icon = "🧹", Category = "MAINTENANCE", Description = "Remove unused dependencies.", Guide = "Cleans up orphan packages and clears the local repository cache.", ManualLaunch = "sudo apt autoremove", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "SSD Trim", Command = "sudo fstrim -av", Icon = "💿", Category = "MAINTENANCE", Description = "Optimize SSD block allocation.", Guide = "Trims all mounted filesystems to maintain SSD longevity and speed.", ManualLaunch = "sudo fstrim -av", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Clear System Logs", Command = "sudo journalctl --vacuum-time=7d", Icon = "📂", Category = "MAINTENANCE", Description = "Purge old journal entries.", Guide = "Reduces disk usage by removing binary logs older than 7 days.", ManualLaunch = "sudo journalctl --vacuum-time=7d", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Clear Temp Cache", Command = "sudo rm -rf /tmp/* && sudo rm -rf /var/tmp/*", Icon = "🖼️", Category = "MAINTENANCE", Description = "Purge temporary system files.", Guide = "Deletes temporary files stored in /tmp and /var/tmp directories.", ManualLaunch = "rm -rf /tmp/*", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Update Grub", Command = "sudo update-grub", Icon = "🏁", Category = "MAINTENANCE", Description = "Refresh bootloader configuration.", Guide = "Regenerates the GRUB boot menu after kernel or partition changes.", ManualLaunch = "sudo update-grub", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Refresh Initramfs", Command = "sudo update-initramfs -u", Icon = "🧠", Category = "MAINTENANCE", Description = "Update initial RAM filesystem.", Guide = "Updates the boot-time RAM image with current drivers and configs.", ManualLaunch = "sudo update-initramfs -u", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Repair Packages", Command = "sudo apt --fix-broken install", Icon = "🔧", Category = "MAINTENANCE", Description = "Fix broken dependency trees.", Guide = "Attempts to resolve and install missing dependencies automatically.", ManualLaunch = "sudo apt install -f", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "Fix Dpkg Lock", Command = "sudo rm /var/lib/dpkg/lock-frontend", Icon = "🔓", Category = "MAINTENANCE", Description = "Remove package manager locks.", Guide = "Forces the release of the APT lock if a previous process crashed.", ManualLaunch = "sudo rm /var/lib/dpkg/lock", IsMacro = true });
            tools.Add(new ToolItem { SpecificName = "System Reboot", Command = "sudo reboot", Icon = "🔄", Category = "MAINTENANCE", Description = "Perform a clean system restart.", Guide = "Gracefully shuts down all services and reboots the workstation.", ManualLaunch = "sudo reboot", IsMacro = true });

            // --- SYSTEM (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Process Monitor", Command = "htop", Icon = "📋", Category = "SYSTEM", Description = "Advanced interactive monitor.", Guide = "Real-time visualization of CPU, RAM, and running processes.", ManualLaunch = "htop" });
            tools.Add(new ToolItem { SpecificName = "System Info", Command = "hostnamectl", Icon = "ℹ️", Category = "SYSTEM", Description = "View architecture and kernel.", Guide = "Displays the hostname, OS version, kernel, and hardware type.", ManualLaunch = "hostnamectl" });
            tools.Add(new ToolItem { SpecificName = "Hardware Lister", Command = "sudo lshw -short", Icon = "💻", Category = "SYSTEM", Description = "Brief hardware configuration.", Guide = "Generates a summary of CPU, Memory, PCI, and Disk hardware.", ManualLaunch = "sudo lshw" });
            tools.Add(new ToolItem { SpecificName = "CPU Architecture", Command = "lscpu", Icon = "⚙️", Category = "SYSTEM", Description = "Detailed processor specifications.", Guide = "Shows cores, threads, cache sizes, and CPU flags.", ManualLaunch = "lscpu" });
            tools.Add(new ToolItem { SpecificName = "Memory Stats", Command = "free -h", Icon = "📊", Category = "SYSTEM", Description = "Analyze RAM and swap usage.", Guide = "Displays used and available physical memory and swap space.", ManualLaunch = "free -h" });
            tools.Add(new ToolItem { SpecificName = "PCI Bus Devices", Command = "lspci", Icon = "🔌", Category = "SYSTEM", Description = "List all internal PCI devices.", Guide = "Enumerates graphics cards, network adapters, and controllers.", ManualLaunch = "lspci" });
            tools.Add(new ToolItem { SpecificName = "USB Bus Devices", Command = "lsusb", Icon = "🖱️", Category = "SYSTEM", Description = "List all connected USB devices.", Guide = "Shows all USB hubs and connected peripherals like mice/drives.", ManualLaunch = "lsusb" });
            tools.Add(new ToolItem { SpecificName = "Kernel Specs", Command = "uname -a", Icon = "🐧", Category = "SYSTEM", Description = "View kernel and build details.", Guide = "Displays the exact kernel version and system build timestamp.", ManualLaunch = "uname -a" });
            tools.Add(new ToolItem { SpecificName = "Loaded Modules", Command = "lsmod", Icon = "📦", Category = "SYSTEM", Description = "List active kernel modules.", Guide = "Shows all drivers and modules currently loaded into the kernel.", ManualLaunch = "lsmod" });
            tools.Add(new ToolItem { SpecificName = "Terminal Shell", Command = "x-terminal-emulator", Icon = "🐚", Category = "SYSTEM", Description = "Open default system terminal.", Guide = "Launches the primary command-line interface for the system.", ManualLaunch = "x-terminal-emulator" });

            // --- ADMIN (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Service Manager", Command = "systemctl list-units --type=service", Icon = "⚙️", Category = "ADMIN", Description = "List and manage background tasks.", Guide = "Monitors the status of systemd service units and their health.", ManualLaunch = "systemctl" });
            tools.Add(new ToolItem { SpecificName = "Partition Editor", Command = "sudo gparted", Icon = "💽", Category = "ADMIN", Description = "Graphical disk management.", Guide = "Advanced tool for partitioning, formatting, and resizing disks.", ManualLaunch = "sudo gparted" });
            tools.Add(new ToolItem { SpecificName = "Real-time Logs", Command = "journalctl -f", Icon = "📜", Category = "ADMIN", Description = "Stream system log messages.", Guide = "Continuously displays the latest system events as they occur.", ManualLaunch = "journalctl -f" });
            tools.Add(new ToolItem { SpecificName = "Task Scheduler", Command = "crontab -l", Icon = "📅", Category = "ADMIN", Description = "View automated cron jobs.", Guide = "Lists scheduled tasks configured for the current user.", ManualLaunch = "crontab -l" });
            tools.Add(new ToolItem { SpecificName = "User List", Command = "cut -d: -f1 /etc/passwd", Icon = "👥", Category = "ADMIN", Description = "List all registered accounts.", Guide = "Retrieves all user identities registered in the system database.", ManualLaunch = "cat /etc/passwd" });
            tools.Add(new ToolItem { SpecificName = "Active Sessions", Command = "who -a", Icon = "👤", Category = "ADMIN", Description = "View currently logged in users.", Guide = "Shows active terminal sessions and remote login users.", ManualLaunch = "who" });
            tools.Add(new ToolItem { SpecificName = "System Uptime", Command = "uptime -p", Icon = "⏱️", Category = "ADMIN", Description = "Check how long system has run.", Guide = "Displays duration since last boot in a human-readable format.", ManualLaunch = "uptime" });
            tools.Add(new ToolItem { SpecificName = "Runlevel Status", Command = "runlevel", Icon = "🏃", Category = "ADMIN", Description = "Check current system state.", Guide = "Identifies the current and previous system operational levels.", ManualLaunch = "runlevel" });
            tools.Add(new ToolItem { SpecificName = "Hostname Config", Command = "cat /etc/hostname", Icon = "🏷️", Category = "ADMIN", Description = "View system network name.", Guide = "Displays the configured network name for this machine.", ManualLaunch = "hostname" });
            tools.Add(new ToolItem { SpecificName = "DMI Table Info", Command = "sudo dmidecode -s system-product-name", Icon = "🗄️", Category = "ADMIN", Description = "View BIOS/Firmware data.", Guide = "Retrieves hardware manufacturing info directly from the BIOS.", ManualLaunch = "sudo dmidecode" });

            // --- SECURITY (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Firewall Status", Command = "sudo ufw status verbose", Icon = "🛡️", Category = "SECURITY", Description = "Audit UFW configurations.", Guide = "Checks the active ruleset and status of the Linux firewall.", ManualLaunch = "sudo ufw status" });
            tools.Add(new ToolItem { SpecificName = "Network Ports", Command = "sudo ss -tulpn", Icon = "🔒", Category = "SECURITY", Description = "Analyze listening services.", Guide = "Identifies which processes are listening on network ports.", ManualLaunch = "sudo ss -tulpn" });
            tools.Add(new ToolItem { SpecificName = "SSH Audit", Command = "sudo journalctl -u ssh", Icon = "🗝️", Category = "SECURITY", Description = "Review SSH login attempts.", Guide = "Filters logs for SSH activity to detect unauthorized access.", ManualLaunch = "sudo journalctl -u ssh" });
            tools.Add(new ToolItem { SpecificName = "Failed Logins", Command = "sudo lastb | head -n 20", Icon = "🆘", Category = "SECURITY", Description = "Check recent failed logins.", Guide = "Displays the most recent unsuccessful authentication attempts.", ManualLaunch = "sudo lastb" });
            tools.Add(new ToolItem { SpecificName = "AppArmor Status", Command = "sudo aa-status", Icon = "🔗", Category = "SECURITY", Description = "Check security profiles.", Guide = "Shows the status of AppArmor profiles and enforced restrictions.", ManualLaunch = "sudo aa-status" });
            tools.Add(new ToolItem { SpecificName = "SELinux Context", Command = "sestatus", Icon = "🧱", Category = "SECURITY", Description = "Check SELinux enforcement.", Guide = "Determines if SELinux is in enforcing, permissive, or disabled mode.", ManualLaunch = "sestatus" });
            tools.Add(new ToolItem { SpecificName = "Password Aging", Command = "chage -l $USER", Icon = "🔑", Category = "SECURITY", Description = "View account security dates.", Guide = "Shows when your password was last changed and when it expires.", ManualLaunch = "chage -l" });
            tools.Add(new ToolItem { SpecificName = "Sudoers Check", Command = "sudo -l", Icon = "🖋️", Category = "SECURITY", Description = "Audit sudo privileges.", Guide = "Lists the specific administrative permissions for your user.", ManualLaunch = "sudo -l" });
            tools.Add(new ToolItem { SpecificName = "File Integrity", Command = "lsattr -a", Icon = "🆘", Category = "SECURITY", Description = "Check file attributes.", Guide = "Displays extended file attributes like 'immutable' or 'append-only'.", ManualLaunch = "lsattr" });
            tools.Add(new ToolItem { SpecificName = "System Entropy", Command = "cat /proc/sys/kernel/random/entropy_avail", Icon = "🎲", Category = "SECURITY", Description = "Analyze randomness pool.", Guide = "Measures available entropy for secure cryptographic operations.", ManualLaunch = "cat /proc/sys/kernel/random/entropy_avail" });

            // --- NETWORK (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "IP Config", Command = "ip addr show", Icon = "🔍", Category = "NETWORK", Description = "Analyze network interfaces.", Guide = "Displays IP addresses, MAC addresses, and interface states.", ManualLaunch = "ip addr" });
            tools.Add(new ToolItem { SpecificName = "DNS Cache Flush", Command = "sudo systemd-resolve --flush-caches", Icon = "🧼", Category = "NETWORK", Description = "Purge local DNS resolver.", Guide = "Clears the systemd-resolved cache to fix domain resolution issues.", ManualLaunch = "sudo systemd-resolve --flush-caches" });
            tools.Add(new ToolItem { SpecificName = "Network Manager", Command = "nmcli device show", Icon = "📡", Category = "NETWORK", Description = "View device configurations.", Guide = "Shows detailed settings for Ethernet, Wi-Fi, and virtual devices.", ManualLaunch = "nmcli device" });
            tools.Add(new ToolItem { SpecificName = "Connectivity Test", Command = "ping -c 4 google.com", Icon = "🔄", Category = "NETWORK", Description = "Check internet latency.", Guide = "Sends 4 ICMP packets to verify connectivity and measure delay.", ManualLaunch = "ping google.com" });
            tools.Add(new ToolItem { SpecificName = "Trace Route", Command = "traceroute google.com", Icon = "📶", Category = "NETWORK", Description = "Map network hop paths.", Guide = "Shows every router and server between you and a destination.", ManualLaunch = "traceroute" });
            tools.Add(new ToolItem { SpecificName = "DNS Query (Dig)", Command = "dig google.com", Icon = "🌐", Category = "NETWORK", Description = "Perform advanced DNS lookup.", Guide = "Retrieves full DNS record data for any domain name.", ManualLaunch = "dig" });
            tools.Add(new ToolItem { SpecificName = "Host Lookup", Command = "host google.com", Icon = "🔗", Category = "NETWORK", Description = "Translate name to IP.", Guide = "Quickly finds the IP address associated with a domain.", ManualLaunch = "host" });
            tools.Add(new ToolItem { SpecificName = "Socket Stats", Command = "ss -s", Icon = "📊", Category = "NETWORK", Description = "View connection summaries.", Guide = "Shows total counts of established TCP, UDP, and RAW sockets.", ManualLaunch = "ss -s" });
            tools.Add(new ToolItem { SpecificName = "Route Table", Command = "ip route", Icon = "🗺️", Category = "NETWORK", Description = "Analyze network routing.", Guide = "Displays the gateway and routing rules for network traffic.", ManualLaunch = "ip route" });
            tools.Add(new ToolItem { SpecificName = "ARP Table", Command = "ip neigh", Icon = "👥", Category = "NETWORK", Description = "Analyze neighbor devices.", Guide = "Lists MAC-to-IP mappings for devices on your local network.", ManualLaunch = "ip neigh" });

            // --- UTILITIES (10 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Terminal Editor", Command = "nano", Icon = "📝", Category = "UTILITIES", Description = "Lightweight text editor.", Guide = "A simple terminal-based editor for modifying config files.", ManualLaunch = "nano" });
            tools.Add(new ToolItem { SpecificName = "File Browser", Command = "xdg-open .", Icon = "📁", Category = "UTILITIES", Description = "Open current directory.", Guide = "Launches the GUI file manager at the current working path.", ManualLaunch = "xdg-open ." });
            tools.Add(new ToolItem { SpecificName = "Ollama AI Core", Command = "ollama run llama3", Icon = "🧠", Category = "UTILITIES", Description = "Local AI deployment.", Guide = "Starts an interactive local session with the Llama3 AI model.", ManualLaunch = "ollama run llama3" });
            tools.Add(new ToolItem { SpecificName = "Calculator (bc)", Command = "bc -l", Icon = "🧮", Category = "UTILITIES", Description = "Precision math engine.", Guide = "Opens an interactive high-precision mathematical calculator.", ManualLaunch = "bc" });
            tools.Add(new ToolItem { SpecificName = "System Calendar", Command = "cal", Icon = "📅", Category = "UTILITIES", Description = "View terminal calendar.", Guide = "Displays the current month's calendar in the terminal.", ManualLaunch = "cal" });
            tools.Add(new ToolItem { SpecificName = "Base64 Encoder", Command = "echo 'JEMTOOLS' | base64", Icon = "🔢", Category = "UTILITIES", Description = "Encode text to Base64.", Guide = "Converts standard text into a Base64-encoded string format.", ManualLaunch = "base64" });
            tools.Add(new ToolItem { SpecificName = "SHA256 Hash", Command = "sha256sum --help", Icon = "💎", Category = "UTILITIES", Description = "Check file integrity.", Guide = "Utility to calculate and verify SHA-256 digital signatures.", ManualLaunch = "sha256sum" });
            tools.Add(new ToolItem { SpecificName = "Password Gen", Command = "openssl rand -base64 12", Icon = "🗝️", Category = "UTILITIES", Description = "Create secure passwords.", Guide = "Generates a 12-character random string for secure usage.", ManualLaunch = "openssl rand" });
            tools.Add(new ToolItem { SpecificName = "Character Map", Command = "unicode --help", Icon = "🔣", Category = "UTILITIES", Description = "View symbol catalog.", Guide = "Accesses the system's character and symbol database info.", ManualLaunch = "unicode" });
            tools.Add(new ToolItem { SpecificName = "Localization", Command = "localectl", Icon = "🌍", Category = "UTILITIES", Description = "View system locale.", Guide = "Checks the current language, keyboard, and region settings.", ManualLaunch = "localectl" });

            // --- JEMBOOT (3 Tools) ---
            tools.Add(new ToolItem { SpecificName = "Block Layout", Command = "lsblk -f", Icon = "🔌", Category = "JEMBOOT", Description = "Map all storage disks.", Guide = "Shows a tree view of all disks, partitions, and UUIDs.", ManualLaunch = "lsblk -f" });
            tools.Add(new ToolItem { SpecificName = "Active Mounts", Command = "mount | column -t", Icon = "💾", Category = "JEMBOOT", Description = "View mounted filesystems.", Guide = "Lists all currently attached storage volumes and their paths.", ManualLaunch = "mount" });
            tools.Add(new ToolItem { SpecificName = "Disk Partitioning", Command = "sudo fdisk -l", Icon = "📀", Category = "JEMBOOT", Description = "View partition tables.", Guide = "Detailed low-level view of disk geometry and partition data.", ManualLaunch = "sudo fdisk -l" });
            // INSTALLERS
            tools.Add(new ToolItem { SpecificName = "Install 7-Zip", Command = "sudo apt install p7zip-full -y || sudo dnf install p7zip -y", Icon = "📦", Category = "INSTALLERS", Description = "Open-source file archiver.", Guide = "Installs p7zip via package manager.", ManualLaunch = "apt install p7zip-full" });
            tools.Add(new ToolItem { SpecificName = "Install WinRAR", Command = "sudo apt install unrar -y || sudo dnf install unrar -y", Icon = "🗜️", Category = "INSTALLERS", Description = "Extraction utility.", Guide = "Installs unrar automatically for your distribution.", ManualLaunch = "apt install unrar" });
            tools.Add(new ToolItem { SpecificName = "Install PeaZip", Command = "flatpak install flathub io.github.peazip.PeaZip -y", Icon = "🗃️", Category = "INSTALLERS", Description = "Free archive manager.", Guide = "Installs PeaZip via Flatpak.", ManualLaunch = "flatpak install peazip" });
            tools.Add(new ToolItem { SpecificName = "Install VS Code", Command = "snap install code --classic", Icon = "💻", Category = "INSTALLERS", Description = "Modern source code editor.", Guide = "Installs Microsoft Visual Studio Code via Snap.", ManualLaunch = "snap install code" });
            tools.Add(new ToolItem { SpecificName = "Install Cursor", Command = "curl -fsSL https://cursor.sh/install | bash", Icon = "🤖", Category = "INSTALLERS", Description = "AI-first code editor.", Guide = "Installs Cursor via official installer.", ManualLaunch = "install cursor" });
            tools.Add(new ToolItem { SpecificName = "Install Eclipse", Command = "snap install eclipse --classic", Icon = "☕", Category = "INSTALLERS", Description = "Java Development IDE.", Guide = "Installs the Eclipse Java development environment.", ManualLaunch = "snap install eclipse" });
            tools.Add(new ToolItem { SpecificName = "Install Blender", Command = "snap install blender --classic", Icon = "🎨", Category = "INSTALLERS", Description = "3D creation suite.", Guide = "Installs Blender via Snap.", ManualLaunch = "snap install blender" });
            tools.Add(new ToolItem { SpecificName = "Install Acrobat", Command = "xdg-open \"https://duckduckgo.com/?q=Linux+PDF+Reader+Adobe\"", Icon = "📄", Category = "INSTALLERS", Description = "PDF viewer alternatives.", Guide = "Adobe Acrobat is not native to Linux; searches for alternatives.", ManualLaunch = "search pdf" });
            tools.Add(new ToolItem { SpecificName = "Install DaVinci Resolve", Command = "xdg-open \"https://www.blackmagicdesign.com/products/davinciresolve\"", Icon = "🎬", Category = "INSTALLERS", Description = "Free video editor.", Guide = "Opens DaVinci Resolve download page (requires manual .zip installation on Linux).", ManualLaunch = "search davinci" });
            tools.Add(new ToolItem { SpecificName = "Install Photoshop CS6 x64", Command = "xdg-open \"https://drive.google.com/file/d/108-MMr552-vNUg4ICd9_zo-ALn5AT7Oq/view?usp=drive_link\"", Icon = "🖼️", Category = "INSTALLERS", Description = "Download Portable CS6 (x64).", Guide = "Opens Google Drive to download the x64 portable version of Photoshop CS6.", ManualLaunch = "download ps cs6" });
            tools.Add(new ToolItem { SpecificName = "Install Photoshop CS6 x86", Command = "xdg-open \"https://drive.google.com/file/d/1bC498LjJy9308a8pHMJRQ1DUyyiMDcJ4/view?usp=drive_link\"", Icon = "🖌️", Category = "INSTALLERS", Description = "Download Portable CS6 (x86).", Guide = "Opens Google Drive to download the x86 portable version of Photoshop CS6.", ManualLaunch = "download ps cs6 32" });
            tools.Add(new ToolItem { SpecificName = "Install Photoshop CS3", Command = "xdg-open \"https://drive.google.com/file/d/1x6DTCVmkEKTGhw4kM1QHUTNx4UktF-gs/view?usp=drive_link\"", Icon = "🎨", Category = "INSTALLERS", Description = "Download Portable CS3.", Guide = "Opens Google Drive to download the portable version of Photoshop CS3.", ManualLaunch = "download ps cs3" });

            tools.Add(new ToolItem { SpecificName = "Install CrystalDiskMark", Command = "xdg-open \"https://drive.google.com/file/d/1d0KpoNteWzGQqlBnj7QyUnHZL0v--xKM/view?usp=drive_link\"", Icon = "💿", Category = "INSTALLERS", Description = "Disk benchmark tool v9.0.2.", Guide = "Opens Google Drive to download CrystalDiskMark 9.0.2 — measures sequential and random read/write speeds.", ManualLaunch = "download crystaldiskmark" });

            tools.Add(new ToolItem { SpecificName = "Install OCCT", Command = "xdg-open \"https://drive.google.com/file/d/1RiDPP8hEecxKsINrR4dgdIhkpUiz6SHn/view?usp=drive_link\"", Icon = "🔥", Category = "INSTALLERS", Description = "PC stability & stress test.", Guide = "Opens Google Drive to download OCCT — tests CPU, GPU, Memory and PSU stability under full load.", ManualLaunch = "download occt" });

            return tools;
        }
    }
}