<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>WindowsSystemToolMenu</RootNamespace>
    <AssemblyName>Jem Tools</AssemblyName>
    <Version>1.2.3</Version>
    <AssemblyVersion>1.2.3.0</AssemblyVersion>
    <FileVersion>1.2.3.0</FileVersion>
    <Company>JEM TOOLS</Company>
    <Product>JEM TOOLS | Admin Edition</Product>
    <Copyright>Copyright © 2026 Jemmy Francisco</Copyright>
    <Description>Professional Windows Administrative Suite</Description>
    <ApplicationIcon>../../assets/jem_logo.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Optimize>true</Optimize>
    <LangVersion>5</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Shared/Models.cs" />
    <Compile Include="Shared/TUIEngine.cs" />
    <Compile Include="Windows/Modules.cs" />
    <Compile Include="macOS/Modules.cs" />
    <Compile Include="Linux/Modules.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
  </ItemGroup>

</Project>
